### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Shiva Shankar",
  "email": "shiva@example.com",
  "password": "12345",
  "bloodGroup": "B+",
  "city": "Lucknow",
  "contact": "9876543210"
}
